### ISSUE TITLE
Tag SCRIPT breaks whole document

### ISSUE THREAD

**Issue by xdan** [diplodoc-platform/transform#652]
### Package version

4.47.3

### Node version

20.16

### Platform

mac

### What steps will reproduce the bug?

```yaml
allowHTML: true
needToSanitizeHtml: false
```

If you use html in a page + allow inserting script, the page becomes broken. You insert all the content into the script tag at the end of the document, and when the browser parser encounters another script tag inside, it thinks that the first one has ended.

### What is the expected behavior?

For documentation it is often important to include examples, I would like to be able to include a script tag

### What do you see instead?

Broken page

### Additional information

I also couldn't find what format the sanitizer options are (sanitizeOptions). The documentation just says Object.
I think it should be like this:

```yaml
allowHTML: true
needToSanitizeHtml: true
sanitizeOptions:
    allowedTags: 
        - script
```
But this does't work
